### ISSUE TITLE
Battle result informing endpoint

### ISSUE THREAD

**Issue by MikhailDeriabin** [Alt-Org/Altzone-Server#122]
[Swagger description](https://swagger.altzone.fi/#/GameData/post_gameData_battle)

[Flowchart diagram](https://github.com/Alt-Org/Altzone-Server/tree/dev/doc/img/game_results)

[ERD on dev branch](https://github.com/Alt-Org/Altzone-Server/blob/dev/doc/img/ERD.png)

- [x] add /gameData/battle POST endpoint

   The endpoint should be able to recognize the type of game data: "result". If the type is "result" the endpoint should generate a special JWT steal token, containing data about who won. More details you can see from the flowchart "Game results informing...". For generating JWT token you most likely need to install [this library](https://www.npmjs.com/package/jsonwebtoken).

  Notice that you should save the game results to the Game collection, which is probably not created yet in DB. Since each Player of the played game can send the data about the result (currently max 4 players), you should also check whenever the game data is already saved or not. The team1 and team2 are player_ids. And the team1Clan and team2Clan fields should be determined by API, they should contain clan_ids of the teams Players

**Comment by PlayJeri** [comment]
@MikhailDeriabin 
There seems to be some conflicting information about the 200 response values between swagger and flowchart.
Swagger res values are steal_token, stock_id and clan_id and flowchart values are steal_token, soulhome_id and room_ids. Which response is correct?

**Comment by MikhailDeriabin** [comment]
@PlayJeri 

It should be as in flowchart. I guess I forgot to update the swagger. It was previously planned that the steal is happening from stock, vut now it should be made from soulhome

**Comment by PlayJeri** [comment]
@MikhailDeriabin 

I published the feature branch now and I have the business logic working.
There is still some work needed before I can create the PR (documentation, naming and possible race condition error testing)

I'm having trouble understanding the UniformResponse decorator.
When I return ServiceError with SEReason NOT_ALLOWED it comes back with 400 status code and there is not FORBIDDEN option to return the 403 specified by the SWAGGER. 

I need some help with this if the UniformResponse decorator is expected to be used here.

If not I can just throw the ForbiddenException in the controller
