### ISSUE TITLE
install Discourse forum

### ISSUE THREAD

**Issue by leolabdev** [Alt-Org/Altzone-Server#133]
our game would benefit from the forum.

e.g. guide:
https://cleavr.io/cleavr-slice/how-to-install-a-discourse-forum

**Comment by MikhailDeriabin** [comment]
@leolabdev 
I would like to get more detailed description about the forum. Why, where etc.

**Comment by MikhailDeriabin** [comment]
@leolabdev 

Could you answer the questions above, otherwise I am closing the issue
