### ISSUE TITLE
Error with CORS

### ISSUE THREAD

**Issue by MikhailDeriabin** [Alt-Org/Altzone-Server#137]
![image(2)](https://github.com/user-attachments/assets/3086f970-527c-4196-bd5f-3c880e1e9f5c)

**Comment by MikhailDeriabin** [comment]
@Skoivumaki 

Now it should be fixed, if not please let me now

**Comment by Skoivumaki** [comment]
@MikhailDeriabin 

CORS was fixed, however Swagger instructions were incorrect.
Swagger: Method DELETE https://altzone.fi/api/profile (No Params)
![image](https://github.com/user-attachments/assets/375cd06f-bf6f-4f0d-855a-5100999ddb4a)

But code in [Altzone-Server](https://github.com/Alt-Org/Altzone-Server/tree/main)/[src](https://github.com/Alt-Org/Altzone-Server/tree/main/src)/[profile](https://github.com/Alt-Org/Altzone-Server/tree/main/src/profile)/profile.controller.ts

`    @Delete('/:_id')
    @Authorize({action: Action.delete, subject: ProfileDto})
    @CheckPermissions()
    @BasicDELETE(ModelName.PROFILE)
    public async delete(@Param() param: _idDto) {
        return this.service.deleteOneById(param._id);
    }`
**Tested to be working** not sure if intended or Swagger was wrong.

**Comment by MikhailDeriabin** [comment]
@Skoivumaki 

Ok, I will check it
