### ISSUE TITLE
Add /fleaMarket/sell endpoint for proposing item to be sold

### ISSUE THREAD

**Issue by MikhailDeriabin** [Alt-Org/Altzone-Server#197]
[Swagger](https://swagger.altzone.fi/#/FleaMarket/post_fleaMarket_sell)
[Flow chart, item selling process](https://github.com/Alt-Org/Altzone-Server/tree/dev/doc/img/flea_market)

Notice that the notifications mechanism is currently under development, you do not have to implement it yourself. If it is not yet implemented just skip the notification sending part, but make all necessary DB operations. If you are unsure whether it is implemented or not you can ask me in this Issue comment section.

- [ ] write /fleaMarket/sell endpoint

**Comment by PlayJeri** [comment]
@MikhailDeriabin 

About the voting schema. Is the organizer_id supposed to be clan_id and should there be an item_id prop to link the item to the voting.

**Comment by PlayJeri** [comment]
@MikhailDeriabin 

Should the Voting schema have a field for the item the voting is about?
The ERD does not have it but how do we know what item the voting is about without a field like that.

**Comment by MikhailDeriabin** [comment]
@PlayJeri 

Sorry for a delay, I was a bit busy last week. 
Yes, I think there could have some field with info about voting item. It can be some abstract field of type any, which holds some additional info about the voting, so that we can make other types of votings in future not only for items. The `type` field can determine what type of this additional info it is.
