### ISSUE TITLE
[request] : Frontend

### ISSUE THREAD

**Issue by leolab1337** [Alt-Org/Altzone-Server#2]
Is it possible to make the "/clan" endpoint accessible without requiring authorization?

**Comment by MikhailDeriabin** [comment]
I think it is not a good idea for data privacy, but I will discuss your request with colleges.

**Comment by MikhailDeriabin** [comment]
Unfortunately the /clan endpoint has to require authentication. Your request can not be satisfied

**Comment by leolab1337** [comment]
requirements have changed , please open the path
![picture](https://github.com/Alt-Org/Altzone-Server/assets/61798137/a2b20023-f8f8-44b4-a2fd-f03ca0643e0b)

**Comment by MikhailDeriabin** [comment]
Now /clan and /clan/:id GET are open to everyone
