### ISSUE TITLE
Add played battles task

### ISSUE THREAD

**Issue by MikhailDeriabin** [Alt-Org/Altzone-Server#204]
[Flow chart](https://github.com/Alt-Org/Altzone-Server/tree/dev/doc/img/daily_task)

[Tasks table](https://docs.google.com/spreadsheets/d/13NA6G8nL_m6A5cQX8_XoBV04XE5zcfWqfQijInlZu8Y/edit?gid=0#gid=0)

[MQTT notifications](https://github.com/Alt-Org/Altzone-Server/tree/dev/doc/img/notifications)

- [ ] Add tracking of played battles

## General description 
You should implement the player tasks logic, that basically means that you need to think about some mechanism of tracking player progress of the tasks. The one I would suggest is in the flow chart _Tasks registration logic_, but if you can find something better you can do it else way.

[This counter](https://github.com/Alt-Org/Altzone-Server/blob/dev/src/common/service/counter/Counter.ts) class can be handy if you need to increase/decrease amount of completed atomic tasks.

Notice that you can not yet track every kind of tasks described in the table.

Notice that it is API responsibility of tracking these tasks, there are no endpoint to which game just send completed tasks. Basically it is a part of the game business logic running on back-end, because it is the only place there we can ensure validity of tasks completion.

When task is completed a notification should be sent to player. It can be done via MQTT protocol, the code for which most likely is not implemented yet, but you can ask me if you are unsure if it is implemented or not. If it is not implemented just skip notification sending. Overall I will make notification sending easy and there will be no need to change much existing code just call couple methods.

**Comment by MikhailDeriabin** [comment]
@PlayJeri 

I have set up the logic for sending notifications. 

They work via MQTT and you can test it in Postman:
1. Create a new collection, for some reason Postman does not allow u to add MQTT queries to the same folder with HTTP
2. Set _mqtt://localhost:1883_ as a URL
3. In authorization tab set username: publisher and password: publisherPassword (this values should come from the .env file I mentioned in Discord)
4. In topics tab set _/player/#_ value, to get all notifications coming to all topics start with _/player/_ and subscribe

After that, when my PR #250 is approved and merged, get the changes from the _dev_ branch to your. Run the `npm i` to install mqtt lib, and then have a look at `playerTask.notifier.ts` class in the playerTasks folder, it has all necessary methods, I believe.

Make sure to create the .env file in the root folder (same as the package.json)

**Comment by PlayJeri** [comment]
@MikhailDeriabin 

I have made some progress on this issue but I could use your opinion about the solution I have created.
There is still work to do but since I'm not sure if my current solution is a what we are looking for and I don't want to spend more time with this solution before I get your opinion on it.

I tried to make the logic so that old completed tasks get removed from the db when new task of same type and frequency is registered.
This way the collection size wouldn't get too big and the queries would run faster and I couldn't come up with reasons why the old completed tasks should be persisted.

The service methods for the task registration and validations are also made in a way that they work with any task type and frequency and not just the played battles type. The methods still need to be optimised and tested more but you can get the general idea.

I tried using the counter class but I found it to be unnecessary.

I published the branch so if you could check out the code and give some feedback.

**Comment by MikhailDeriabin** [comment]
@PlayJeri 

I have committed example implementation of the atomic task registering (only for daily tasks) in _playerTasks.service.ts_.

Overall your idea is right and we do not need to save any history of the tasks at least for now. The `PlayerTasks` main purpose is to help track the tasks. If we will need any historical data, we will create a separate collection for it, and the `PlayerTasks` collection will not be changed.

I would suggest to not delete the old tasks, but instead just update `startedAt` and `completedAt` fields when required. This you can see in my implementation. I think it introduces a bit less queries to DB.

My first idea was to have multiple arrays with tasks for each day, week and month in `PlayerTasks` collection, the one, which is closer to the JSON file with all tasks. With such structure we do not need to worry if there will be a need to add two or more same tasks for the same day, but your solution should be fine as well at least for now.

![image](https://github.com/user-attachments/assets/a0b66705-4465-46df-86cf-8e24a90aa75b)


Some other notes:

- You should not throw BadRequestException in `createTaskProgress()` on the service level and instead throw a ServiceError.
- The `PlayerTaskNotifier` should have the `NotificationResource` equals to `"daily_task"` not to the type, as you can see in the flow chart. There are no frequency data. Please reverse the made changes to the class and to the `NotificationResource` enum.
