### ISSUE TITLE
add /leaderboard endpoint for retrieving data of top Clans and Players

### ISSUE THREAD

**Issue by MikhailDeriabin** [Alt-Org/Altzone-Server#207]
[Swagger](https://swagger.altzone.fi/#/Leaderboard/get_leaderboard)

[Flow chart](https://github.com/Alt-Org/Altzone-Server/tree/dev/doc/img/leader_board)

The leaderboard is basically just Players and Clan lists that are sorted by `points` field. We expect that it will be a great point of interest among players and therefore the result must be cached, otherwise it can add overhead to DB. The caching should be implemented with use of Redis DB, which instance is added to the _docker-compose_ file.  You can read about caching in Nest [here](https://docs.nestjs.com/techniques/caching), you can install any required libraries for that.

There are some env variables defined for redis:
- REDIS_PASSWORD=mySecretPassword
- REDIS_HOST=localhost
- REDIS_PORT=6379

You should set up connection to redis as it is done for mongo in _app.module.ts_, where first try to read the var from .env file and if it is not found just use hard coded string value. If you need to set some additional vars for redis or API you can set them in _docker-compose.yml_ file in redis _environment_ section.

Notice that the player tasks (points for Clans) and player's own points collection logic are basically the same.

- [x] Add leaderboard for Clans
- [x] Add leaderboard for Players

**Comment by PlayJeri** [comment]
@MikhailDeriabin 

I got the logic working but in my opinion the code would be a bit cleaner if the /leaderboard would be divided to two endpoints (/leaderboard/clan and /leaderboard/player) but it can be done with the query parameter option. The separate endpoints would allow the use of CacheInterceptor decorator that would make the code more readable.

Then we need to add the points to player and clan schemas to filter the results.
Should I add them in this branch?
