### ISSUE TITLE
Install Strapi CMS on the Server

### ISSUE THREAD

**Issue by leolab1337** [Alt-Org/Altzone-Server#29]
We need to set up Strapi CMS on our server for content management purposes

Refer to the [Strapi installation documentation](https://docs.strapi.io/dev-docs/installation) and [Strapi Docker documentation](https://docs.strapi.io/dev-docs/installation/docker) for detailed instructions.

For convenience and easier management, I recommend using the @strapi-community/dockerize tool to containerize the Strapi application. This can simplify deployment and scaling.

Thank you!

**Comment by MikhailDeriabin** [comment]
it is done now

**Comment by leolab1337** [comment]
Hello, there is a problem. We have to run it in development mode to be able to define schemas.
![image](https://github.com/Alt-Org/Altzone-Server/assets/61798137/d0640d4f-24ba-4f69-ba48-d6a66789461b)
