### ISSUE TITLE
Bug: Unable to create a clan without gameCoins

### ISSUE THREAD

**Issue by Skoivumaki** [Alt-Org/Altzone-Server#316]
## What doesn't work?

Unable to create a clan with the data in reproduce step: **3.**
API Response 400:
```
{
    "statusCode": 400,
    "errors": [
        {
            "response": "NOT_NUMBER",
            "status": 400,
            "message": "gameCoins must be an integer number",
            "name": "",
            "reason": "NOT_NUMBER",
            "field": "gameCoins",
            "value": null,
            "additional": "isInt",
            "statusCode": 400,
            "objectType": "APIError"
        }
    ]
}
```
If we include `"gameCoins": 200` in POST, request will succeed. Even thought gameCoins shouldnt be required anymore, unless Im missing something?

## What is the endpoint and method? (if applicable)

Endpoint: https://altzone.fi/api/clan

Method: POST

## How can it be reproduced?

1. Use token of an account that isnt in a clan
2. Use clan creation endpoint: https://altzone.fi/api/clan
3. raw request body:
```
{
    "name": "asdfasdf",
    "tag": "asdfasdf",
    "phrase": "asdfasdf",
    "labels": [
        "itsenäiset"
    ],
    "isOpen": true
}
```

## What should it do instead?

Request should 201 without gameCoins

## Anything else you want to add?

Using https://devapi.altzone.fi/clan with the same data of 3. request is successful...
Tested in frontend and Postman, got same results.

**Comment by MikhailDeriabin** [comment]
@Skoivumaki 

The production build ( https://altzone.fi/api ) is not yet shifted to the newest build, but instead uses the build that was before (release-03-10-2024).

The latest release, which functions you are trying to use can be found from https://devapi.altzone.fi/latest-release

In short, there are 3 builds that is used for different purposes:

- prod
- in-between
- dev

The dev build is used to make hot fixes and has the latest features, however it should not be used broadly, only when there is a critical and urgent bug fix, that need to be resolved "now and here".

The in-between build is made for frontends (site and game) to have time to make use of the new release features or changes. After a new release coming this in-between build is becoming a new prod, and after that shift the in-between build is changed to the new release build. This flow ensures that the clients using the prod build do not brake.

The prod build is always previous release build.

So what you wanna do is to make required changes on client using the in-between build url, and then new release comes, just change this url to the prod.

If you have no further questions, you can close the issue
