### ISSUE TITLE
Bug: /playerTasks returns 404

### ISSUE THREAD

**Issue by MikhailDeriabin** [Alt-Org/Altzone-Server#329]
## What doesn't work?

/playerTasks does not return any tasks for a player

## What is the endpoint and method? (if applicable)

Endpoint: /playerTasks

Method: GET

## How can it be reproduced?

1. make a request to /playerTasks with auth header

## What should it do instead?

Return a list of player tasks

**Comment by MikhailDeriabin** [comment]
@BillTheBeast 

I think I will fix the bug tomorrow, at this point it is possible to put the fixed version to the _/latest-release_ version, so you can use that build, not _dev_

**Comment by BillTheBeast** [comment]
This is back now as a result of the reformat.

Probably because the file that contained these was wiped.
