### ISSUE TITLE
Question: Is the GameStatistics fieldobject that Player contains supposed to be usable yet or not.

### ISSUE THREAD

**Issue by BillTheBeast** [Alt-Org/Altzone-Server#334]
I'm asking this since swagger says they should be there but when I check the json that is returned from the call this is either missing or essentially empty.

Not tagging this as a bug yet since I don't know if it's supposed to be ready and is broken or teh swagger is just wrong.

**Comment by MikhailDeriabin** [comment]
It does work in a way that the player should have some activity before he / she will have the statistics.

You can try to send a message to the chat and the statistics should appear in this `gameStatistics` object. There are also played battles and won battles amounts fields, but they will work, when the player inform the API about played battle via _/gameData_ endpoint, I am not sure if this was added to the game or not yet.
