### ISSUE TITLE
Question: A method to get all items (furniture) in a stock

### ISSUE THREAD

**Issue by BillTheBeast** [Alt-Org/Altzone-Server#343]
Is there currently a method to get all the items that a clan owns from the server?

There seems to have been a endpoint call at one point doing this, but is seems to not work anymore and there doesn't appear to be a endpoint for this currently in the swagger either.

If there isn't one then this should be changed into a feature request to add a method to do this.

**Comment by MikhailDeriabin** [comment]
There are no such endpoint, I will add an issue for that

**Comment by MikhailDeriabin** [comment]
@BillTheBeast 

How it should work? Do you want to get all items of a clan, or from _Soul Home_ and _Stock_ separately?

**Comment by MikhailDeriabin** [comment]
ok
