### ISSUE TITLE
Feature request: Add GET voting/ to get all of the "pollobjects" that the clan has

### ISSUE THREAD

**Issue by BillTheBeast** [Alt-Org/Altzone-Server#344]
## What do you want to see in the API?

GET voting/ that returns all "pollobjects" the clan has

This seems to be the only actual endpoint that is missing from the swagger.

**Comment by MikhailDeriabin** [comment]
@BillTheBeast 

Ok, it will be added in the later sprints.

**Comment by PlayJeri** [comment]
@MikhailDeriabin 

Should I start working on this?

**Comment by MikhailDeriabin** [comment]
@PlayJeri 

Sure
