### ISSUE TITLE
[CORS_PROBLEM] : preflightMissingAllowOriginHeader

### ISSUE THREAD

**Issue by leolab1337** [Alt-Org/Altzone-Server#4]
A cors problem, a possible solution might be found here : https://stackoverflow.com/questions/67100674/cors-problem-preflightmissingalloworiginheader-express-gateway-and-axios
![cors](https://github.com/Alt-Org/Altzone-Server/assets/61798137/58756e9f-046a-45a1-8356-e4d2971a8f05)

**Comment by MikhailDeriabin** [comment]
I have added the new site URL to CORS on API, now it does work.
I am closing this issue
