### ISSUE TITLE
CORS Error 500 on the image galleries page on the dev subdomain

### ISSUE THREAD

**Issue by leolab1337** [Alt-Org/Altzone-Server#76]
![image](https://github.com/user-attachments/assets/02d9d3a9-397b-4716-b1b7-76f1e2672e7f)

![image](https://github.com/user-attachments/assets/3e51835a-7db2-4427-8bcd-2fa1a295cf00)

![image](https://github.com/user-attachments/assets/d462b633-1e7b-4a3c-9e1e-208d1ed4a117)

https://dev.altzone.fi/en/picture-galleries

**Comment by MikhailDeriabin** [comment]
I can not replicate the CORS error. I did try to load this in Firefox, Chrome and Edge.

Could you try to clear the cache of your browser, if it did not help provide more information about the error:

1. What message do you get in the console?
2. What browser do you use?
3. Are you logged in?
4. Did you accepted the use of cookies or not?

**Comment by leolab1337** [comment]
![image](https://github.com/user-attachments/assets/e0794e59-5677-42a0-adc0-100a1f9b986f)

**Comment by MikhailDeriabin** [comment]
You can try it now, but if it did not help, please write down answers to previous questions. You can add screenshots as well if you want, but please type answers in the first place, not screenshots only

**Comment by MikhailDeriabin** [comment]
@leolab1337 is it resolved now?
